// <auto-generated />
using System;
using Infrastructure.EntityFramework.Snapshotting.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(SnapshotStoreDbContext))]
    [Migration("20180913211144_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.EntityFramework.Snapshotting.Database.SnapshotEntity", b =>
                {
                    b.Property<string>("StreamName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Payload");

                    b.Property<DateTime>("Timestamp");

                    b.Property<long>("Version");

                    b.HasKey("StreamName");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
